version: '3.8'

services:
  # 1. Veritabanı (MSSQL)
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: society_sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=GucluBirSifre123!
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  # 2. Önbellek (Redis)
  redis:
    image: redis:latest
    container_name: society_redis
    ports:
      - "6379:6379"

  # 3. Depolama (MinIO)
  minio:
    image: minio/minio
    container_name: society_minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:  # <-- DÜZELTİLDİ: İçeri alındı
      - "9005:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  sql_data:
  minio_data: